@startuml

Actor User as user
boundary "index.jsp" as request
participant "Request" as req
participant LogicFacade
participant OrderMapper
database "Database" as database

user -> request : user clicks "send"
request -> req : [for each input] validate()
req -> request : if fail: show error message
request -> user
user -> request : user clicks send with valid input
request -> req : [for each input] validate()

req -> LogicFacade : createOrder()
LogicFacade -> OrderMapper : createOrder()
OrderMapper -> database : creates order
database -> OrderMapper : confirm success
OrderMapper -> LogicFacade : return
LogicFacade -> req : return
req -> request : display success message
request -> user

@enduml