@startuml

Actor User as user
boundary "vieworder.jsp" as vieworder
boundary "materials-bill.jsp" as matbill
participant "Bill" as bill
participant "BillCalculator" as billcalc
participant "CarportGenerator" as carportgen
participant "ShedGenerator" as shedgen
participant LogicFacade
participant OrderMapper
participant MaterialsMapper
database "Database" as database

user -> vieworder : user clicks "stykliste"
vieworder -> bill : execute()
bill -> LogicFacade : getBillLines()
LogicFacade -> OrderMapper : getOrder()
OrderMapper -> database : preparedStatement
database -> OrderMapper : resultSet
OrderMapper -> LogicFacade : return
LogicFacade -> billcalc : calculateBillFromOrder()
billcalc -> billcalc : figure out carport type
billcalc -> LogicFacade : getTheseCategories()
LogicFacade -> MaterialsMapper : getTheseCategories()
MaterialsMapper -> database : preparedStatement
database -> MaterialsMapper : resultSet
MaterialsMapper -> LogicFacade : return
LogicFacade -> billcalc : return

note right of billcalc
repeat following
end note

billcalc -> carportgen : underSternsBredderFrontAndBack()
carportgen -> billcalc : return Category
billcalc -> shedgen : boardsForShed()
shedgen -> billcalc : return Category

note right of billcalc
repeat above for each
category needed
end note

billcalc -> LogicFacade : return ArrayList<Category>
LogicFacade -> bill : return ArrayList<Category>
bill -> matbill
matbill -> user : display bill of materials

@enduml