USE FogByggemarked;
set foreign_key_checks=0;
TRUNCATE TABLE bill;
TRUNCATE TABLE category;
TRUNCATE TABLE material_to_category;
TRUNCATE TABLE materials;
TRUNCATE TABLE orders;
TRUNCATE TABLE sheds;
TRUNCATE TABLE variant;
set foreign_key_checks=1;
SET SQL_MODE =  'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('3600', '25', '200', '25x200 mm. trykimp. Brædt',20);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('5400', '25', '200', '25x200 mm. trykimp. Brædt',25);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('3600', '25', '125', '25x125 mm. trykimp. Brædt',20);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('5400', '25', '125', '25x125 mm. trykimp. Brædt',25);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('4200', '38', '73', '38x73 mm. Lægte ubh.',50);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('2700', '45', '95', '45x95 mm. Reglar ub.',60);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('2400', '45', '95', '45x95 mm. Reglar ub.',60);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('6000', '45', '195', '45x195 mm. spærtræ ubh.',40);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('4800', '45', '195', '45x195 mm. spærtræ ubh.',35);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('3000', '97', '97', '97x97 mm. trykimp. Stolpe',21);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('2100', '19', '100', '19x100 mm. trykimp. Brædt',15);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('5400', '19', '100', '19x100 mm. trykimp. Brædt',20);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('3600', '19', '100', '19x100 mm. trykimp. Brædt',18);
INSERT INTO `FogByggemarked`.`materials` (`length`, `width`, `name`,`price`) VALUES ('6000', '109', 'Plastmo Ecolite blåtonet(600 x 109)',61);
INSERT INTO `FogByggemarked`.`materials` (`length`, `width`, `name`,`price`) VALUES ('3600', '109', 'Plastmo Ecolite blåtonet(360 x 109)',61);

INSERT INTO `FogByggemarked`.`materials` (`length`, `amount`, `name`,`price`) VALUES ('0', '200', 'plastmo bundskruer 200 stk.',81);
INSERT INTO `FogByggemarked`.`materials` (`length`, `name`,`price`) VALUES ('10000','hulbånd 1x20 mm. 10 mtr.',91);
INSERT INTO `FogByggemarked`.`materials` (`name`,`price`) VALUES ('universal 190 mm højre',12);
INSERT INTO `FogByggemarked`.`materials` (`name`,`price`) VALUES ('universal 190 mm venstre',22);
INSERT INTO `FogByggemarked`.`materials` (`amount`, `name`,`price`) VALUES ('200', '4,5 x 60 mm. skruer 200 stk.',32);
INSERT INTO `FogByggemarked`.`materials` (`amount`, `name`,`price`) VALUES ('250', '4,0 x 50 mm. beslagskruer 250 stk.',42);
INSERT INTO `FogByggemarked`.`materials` (`length`, `width`, `name`,`price`) VALUES ('1200', '10', 'bræddebolt 10 x 120 mm.',52);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('400', '11', '40', 'firkantskiver 40x40x11mm',62);
INSERT INTO `FogByggemarked`.`materials` (`length`, `width`, `amount`, `name`,`price`) VALUES ('700', '5', '400', '4.5 x 70 mm. Skruer 400 stk.',72);
INSERT INTO `FogByggemarked`.`materials` (`length`, `width`, `amount`,`name`,`price`) VALUES ('500', '5', '300', '4,5 x 50 mm. Skruer 300 stk.',82);
INSERT INTO `FogByggemarked`.`materials` (`name`,`price`) VALUES ('stalddørsgreb 50x75',92);
INSERT INTO `FogByggemarked`.`materials` (`length`, `name`,`price`) VALUES ('3900', 't hængsel 390 mm',13);
INSERT INTO `FogByggemarked`.`materials` (`name`,`price`) VALUES ('vinkelbeslag 35',23);

INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('4800', '25', '150', '25x150 mm. trykimp. Bræt',18);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('6000', '25', '150', '25x150 mm. trykimp. Bræt',18);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('2400', '19', '100', '19x100 mm. trykimp. Bræt',18);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('5400', '25', '50', '25x50 mm. trykimp. Bræt',18);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('5400', '38', '73', '38x73 mm. taglægte T1',18);
INSERT INTO `FogByggemarked`.`materials` (`length`, `height`, `width`, `name`,`price`) VALUES ('4200', '38', '73', '38x73 mm. taglægte T1',18);
INSERT INTO `FogByggemarked`.`materials` (`name`,`price`) VALUES ('B & C Dobbelt -s sort',18);
INSERT INTO `FogByggemarked`.`materials` (`name`,`price`) VALUES ('B & C Rygsten sort',18);
INSERT INTO `FogByggemarked`.`materials` (`name`,`price`) VALUES ('B & C Toplægte holder',18);
INSERT INTO `FogByggemarked`.`materials` (`name`,`price`) VALUES ('B & C rygstensbeslag',18);
INSERT INTO `FogByggemarked`.`materials` (`name`,`price`,`amount`) VALUES ('B & C tagstens bindere & nakkekroge', 20,500);
INSERT INTO `FogByggemarked`.`materials` (`amount`,`name`,`price`) VALUES ('100', '5,0 x 100 mm. skruer 100 stk.', 30);


INSERT INTO `FogByggemarked`.`orders` VALUES (1,300,300,300,0, '2020-05-05 12:30:56');
INSERT INTO `FogByggemarked`.`orders` VALUES (2,400,400,400,0, '2020-07-06 12:30:56');
INSERT INTO `FogByggemarked`.`orders` VALUES (3,500,500,500,0, '2020-10-07 12:30:56');
INSERT INTO `FogByggemarked`.`orders` VALUES (4,600,600,600,0, '2020-11-08 12:30:56');
INSERT INTO `FogByggemarked`.`orders` VALUES (5,300,300,300,21, '2020-02-09 12:30:56');
INSERT INTO `FogByggemarked`.`orders` VALUES (6,400,400,400,22, '2020-12-10 12:30:56');
INSERT INTO `FogByggemarked`.`orders` VALUES (7,500,500,500,23, '2020-01-11 12:30:56');
INSERT INTO `FogByggemarked`.`orders` VALUES (8,600,600,600,25, '2020-03-12 12:30:56');
INSERT INTO `FogByggemarked`.`orders` VALUES (9,200,200,200,0, '2020-02-13 12:30:56');
INSERT INTO `FogByggemarked`.`sheds` VALUES (1,5,50,50);
INSERT INTO `FogByggemarked`.`sheds` VALUES (2,6,60,60);
INSERT INTO `FogByggemarked`.`sheds` VALUES (3,7,70,70);
INSERT INTO `FogByggemarked`.`sheds` VALUES (4,8,80,80);
INSERT INTO `FogByggemarked`.`sheds` VALUES (5,1,150,150);

INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('understernbrædder til for & bag ende');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('understernbrædder til siderne');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('oversternbrædder til forenden');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('oversternbrædder til siderne');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('til z på bagside af dør');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('løsholter til skur gavle');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('løsholter til skur sider');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Remme i sider, sadles ned i stolpe');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Remme i sider, sadles ned i stolper (skur del, deles)');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Spær, monteres på rem');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Stolper nedgraves 90 cm. i jord');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('til beklædning af skur 1 på 2');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('vandbrædt på stern i sider');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('vandbrædt på stern i forende');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('tagplader monteres på spær');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Skruer til tagplader');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til vindkryds på spær');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til montering af spær på rem - højre');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til montering af spær på rem - venstre');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til montering af stern&vandbrædt');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til montering af universalbeslag + hulbånd');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til montering af rem på stolper - bolte');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til montering af rem på stolper - skiver');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('til montering af yderste beklædning');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('til montering af inderste beklædning');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til lås på dør i sku r');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til skurdør');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til montering af løsholter i skur');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Vindskeder på rejsning');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('beklædning af gavle 1 på 2');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('til montering oven på tagfodslægte');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('til montering på spær, 7 rækker lægter på hver skiftevis 1 hel & 1 halv lægte');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('toplægte til montering af rygsten lægges i toplægte holder');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('monteres på taglægter 6 rækker af 24 sten på hver side af taget');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('monteres på toplægte med medfølgende beslag se tagstens vejledning');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('monteres på toppen af spæret (til toplægte)');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til montering af rygsten');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('til montering af tagsten, alle ydersten + hver anden fastgøres');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til montering af Stern, vindskeder, vindkryds & vand bræt');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('Til montering af universalbeslag + toplægte');
INSERT INTO `FogByggemarked`.`category` (decription) VALUES ('til taglægter');

INSERT INTO `FogByggemarked`.`variant` (variant_name,category_id) VALUES ('Plastmo Ecolite Blaaligt', 15);
INSERT INTO `FogByggemarked`.`variant`(variant_name,category_id) VALUES ('Plastmo Ecolite Groonligt', 15);
INSERT INTO `FogByggemarked`.`variant` (variant_name,category_id)VALUES ('Plastmo Ecolite Gulligt', 15);

INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (1,1);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (2,1);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (1,2);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (2,2);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (3,3);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (4,3);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (3,4);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (4,4);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (5,5);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (6,6);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (7,6);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (6,7);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (7,7);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (8,8);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (9,8);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (8,9);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (9,9);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (8,10);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (9,10);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (10,11);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (11,12);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (12,12);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (13,12);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (11,13);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (12,13);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (13,13);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (11,14);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (12,14);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (13,14);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (14,15);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (15,15);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (16,16);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (17,17);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (18,18);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (19,19);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (20,20);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (21,21);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (22,22);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (23,23);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (24,24);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (25,25);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (26,26);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (27,27);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (28,28);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (1,29);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (2,29);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (29,29);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (30,29);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (11,30);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (12,30);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (13,30);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (31,30);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (32,31);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (33,32);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (34,32);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (33,33);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (34,33);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (35,34);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (36,35);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (37,36);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (38,37);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (39,38);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (20,39);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (21,40);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (40,41);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (29,1);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (30,1);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (29,2);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (30,2);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (31,12);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (31,13);
INSERT INTO `FogByggemarked`.`material_to_category` (`material_id`,`category_id`) VAlUES (31,14);