USE FogByggemareked;
SET SQL_MODE =  'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('360', '25', '200', '25x200 mm. trykimp. Brædt');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('540', '25', '200', '25x200 mm. trykimp. Brædt');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('360', '25', '125', '25x125mm. trykimp. Brædt');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('600', '45', '195', '45x195 mm. spærtræ ubh.');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('420', '38', '73', '38x73 mm. Lægte ubh.');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('270', '45', '95', '45x95 mm. Reglar ub.');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('540', '25', '125', '25x125mm. trykimp. Brædt');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('240', '45', '95', '45x95 mm. Reglar ub.');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('480', '45', '195', '45x195 mm. spærtræ ubh.');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('300', '97', '97', '97x97 mm. trykimp. Stolpe');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('210', '19', '100', '19x100 mm. trykimp. Brædt');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('540', '19', '100', '19x100 mm. trykimp. Brædt');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('360', '19', '100', '19x100 mm. trykimp. Brædt');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `width`, `name`) VALUES ('600', '109', 'Plastmo Ecolite blåtonet(600 x 109)');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `width`, `name`) VALUES ('360', '109', 'Plastmo Ecolite blåtonet(360 x 109)');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `amount`, `name`) VALUES ('0', '200', 'plastmo bundskruer 200 stk.');
INSERT INTO `fogbyggemareked`.`materials` (`name`) VALUES ('hulbånd 1x20 mm. 10 mtr.');
INSERT INTO `fogbyggemareked`.`materials` (`name`) VALUES ('universal 190 mm højre');
INSERT INTO `fogbyggemareked`.`materials` (`name`) VALUES ('universal 190 mm venstre');
INSERT INTO `fogbyggemareked`.`materials` (`amount`, `name`) VALUES ('200', '4,5 x 60 mm. skruer 200 stk.');
INSERT INTO `fogbyggemareked`.`materials` (`amount`, `name`) VALUES ('250', '4,0 x 50 mm. beslagskruer 250 stk.');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `width`, `name`) VALUES ('120', '10', 'bræddebolt 10 x 120 mm.');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `height`, `width`, `name`) VALUES ('40', '11', '40', 'firkantskiver 40x40x11mm');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `width`, `amount`, `name`) VALUES ('70', '5', '400', '5 x 70 mm. Skruer 400 stk.');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `width`, `name`) VALUES ('50', '5', '4,5 x 50 mm. Skruer 300 stk.');
INSERT INTO `fogbyggemareked`.`materials` (`name`) VALUES ('stalddørsgreb 50x75');
INSERT INTO `fogbyggemareked`.`materials` (`length`, `name`) VALUES ('390', 't hængsel 390 mm');
INSERT INTO `fogbyggemareked`.`materials` (`name`) VALUES ('vinkelbeslag 35');
INSERT INTO `orders` VALUES (1,300,300,300,0);
INSERT INTO `orders` VALUES (2,400,400,400,0);
INSERT INTO `orders` VALUES (3,500,500,500,0);
INSERT INTO `orders` VALUES (4,600,600,600,0);
INSERT INTO `orders` VALUES (5,300,300,300,10);
INSERT INTO `orders` VALUES (6,400,400,400,15);
INSERT INTO `orders` VALUES (7,500,500,500,20);
INSERT INTO `orders` VALUES (8,600,600,600,25);
INSERT INTO `orders` VALUES (9,200,200,200,0);
INSERT INTO `sheds` VALUES (1,5,50,50);
INSERT INTO `sheds` VALUES (2,6,60,60);
INSERT INTO `sheds` VALUES (3,7,70,70);
INSERT INTO `sheds` VALUES (4,8,80,80);
